spring:
  application:
    name: hotel
  data:
    mongodb:
      uri: mongodb+srv://hbib:Azerty%409911@cluster0.br7eade.mongodb.net/PFE?retryWrites=true&w=majority
  profiles:
    active: amadeus
server:
  port: 8060




logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG

